[build]
builder = "NIXPACKS"
buildCommand = "dotnet publish src/HostingQr.Api -c Release"

[deploy]
startCommand = "dotnet src/HostingQr.Api/bin/Release/net9.0/publish/HostingQr.Api.dll"
healthcheckPath = "/api/ping"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
